kwikSort_iterate.cpp
NAME
kwikSort_iterate.cpp - Implementation of a non-recursive (iterative) quicksort algorithm using a stack.
SYNOPSIS
#include <iostream>
#include <stack>
#include <vector>
Functions
int main ()
int partition (vector< int > &set, int start, int end)
Partitions a subarray around a pivot for quicksort.
void quickSort (vector< int > &set, int start, int end)
Performs an iterative (non-recursive) quicksort on a vector.
Detailed Description
Implementation of a non-recursive (iterative) quicksort algorithm using a stack.
This program demonstrates an iterative version of the quicksort algorithm. It replaces recursion with an explicit stack to manage subarray partitions.
Author:
David J. Devney
Date
2025-02-15 Version:
 1.0 @course CSCI 331
See also:
 partition() See also:
 quickSort()
Warning:
 Ensure sufficient stack capacity for large data sets. Known bug:
 None currently known. To-do:
 Extend to support descending order sorting or custom comparators.
Definition in file kwikSort_iterate.cpp.
Function Documentation
int main ()
Examples
/workspaces/HW_3_331/kwikSort_iterate.cpp.
Definition at line 137 of file kwikSort_iterate.cpp..PP
{
    vector<int> set = {10, 7, 8, 9, 1, 5};
    cout << "Original array: ";
    for (int num : set)
    {
        cout << num << " ";
    }
    cout << endl;
    quickSort(set, 0, set.size() - 1);
    cout << "Sorted array: ";
    for (int num : set)
    {
        cout << num << " ";
    }
    cout << endl;
    return 0;
}
References quickSort().
int partition (vector< int > & set, int start, int end)
Partitions a subarray around a pivot for quicksort. The partition function selects a pivot value and reorders the subarray such that all elements less than the pivot are moved before it, and all elements greater than or equal to the pivot are moved after it.
Parameters
set The vector of integers to partition.
start The starting index of the subarray to partition.
end The ending index of the subarray to partition.
Precondition:
 start and end must be valid indices within the bounds of set. Postcondition:
 Elements in set are rearranged such that all elements before the pivot are smaller and all elements after are greater or equal.
Returns
The index position of the pivot after partitioning.
See also:
 quickSort()
Note
Uses median-of-three pivot selection for improved performance.
Examples
/workspaces/HW_3_331/kwikSort_iterate.cpp.
Definition at line 52 of file kwikSort_iterate.cpp..PP
{
    int pivotValue, pivotIndex, mid;
    mid = (start + end) / 2;
    swap(set[start], set[mid]);
    pivotIndex = start;
    pivotValue = set[start];
    for (int scan = start + 1; scan <= end; scan++)
    {
        if (set[scan] < pivotValue)
        {
            pivotIndex++;
            swap(set[pivotIndex], set[scan]);
        }
    }
    swap(set[start], set[pivotIndex]);
    return pivotIndex;
}
Referenced by quickSort().
void quickSort (vector< int > & set, int start, int end)
Performs an iterative (non-recursive) quicksort on a vector. This function sorts a vector of integers in ascending order using the quicksort algorithm implemented with an explicit stack instead of recursive function calls.
Parameters
set The vector of integers to be sorted.
start The starting index of the vector (typically 0).
end The ending index of the vector (typically set.size() - 1).
Precondition:
 start and end must be valid indices in set, with start <= end. Postcondition:
 The vector set will be sorted in ascending order.
Returns
void
See also:
 partition() Test case:
 Example:
vector<int> nums = {10, 7, 8, 9, 1, 5};
quickSort(nums, 0, nums.size() - 1);
// nums is now {1, 5, 7, 8, 9, 10}
Examples
/workspaces/HW_3_331/kwikSort_iterate.cpp.
Definition at line 99 of file kwikSort_iterate.cpp..PP
{
    stack<pair<int, int>> s;
    s.push({start, end});
    
    while (!s.empty())
    {
        int start = s.top().first;
        int end = s.top().second;
        s.pop();
        if (start < end)
        {
            int p = partition(set, start, end);
            s.push({start, p - 1});
            s.push({p + 1, end});
        }
    }
}
References partition().
Referenced by main().
Author
Generated automatically by Doxygen for kwikSort_iterative from the source code.